In [ ]:
# Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

# Purpose of NumPy:
#1.Efficient Data Storage and Computation: NumPy allows the creation of arrays that are more efficient in terms of memory and performance than traditional Python lists. Its arrays are homogeneous (contain elements of the same type), which reduces overhead and enables faster processing.
#2.Support for Multi-dimensional Arrays: NumPy supports n-dimensional arrays (ndarray), making it easy to handle complex datasets like matrices, images, or higher-dimensional data, which are essential in scientific computing.
#3.Optimized Numerical Computation: It includes a vast array of optimized functions for performing mathematical operations like linear algebra, Fourier transforms, statistical operations, and random number generation, making it essential for numerical tasks.
#4.Interoperability with Other Libraries: Many scientific libraries in Python, such as Pandas, SciPy, Matplotlib, and TensorFlow, are built on top of or integrate closely with NumPy. This makes it a core component in the Python ecosystem for numerical and scientific computing.

# Advantage of numpy :
# 1.High Performance: Faster computations compared to Python lists due to efficient memory usage and C-based implementation.
#2.Memory Efficiency: Arrays store data more compactly than lists.
#3.Vectorization: Allows element-wise operations without loops, enhancing speed and simplicity.
#4.Broadcasting: Enables operations on arrays of different shapes without manual reshaping.
#5.Extensive Mathematical Functions: Provides built-in support for complex mathematical and statistical operations.
#6.Interoperability: Works seamlessly with other scientific libraries like Pandas, SciPy, and TensorFlow.

# NumPy enhances Python's capabilities for scientific computing and data analysis by providing efficient array handling,
#performance optimizations, a rich set of mathematical tools, and the ability to interface with lower-level languages for speed and efficiency.

In [2]:
# Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

# In NumPy, both np.mean() and np.average() calculate the average of array elements,
#but they have some differences in functionality and use cases.

# np.mean() :
# Purpose: Calculates the simple arithmetic mean (average) of array elements.
# Syntax: np.mean(array, axis=None)
# Weights: Does not support weighting; each element contributes equally to the mean.
# Use Case: Use when you want a straightforward, unweighted average of all elements.

# Example:
import numpy as np
a = np.array([1, 2, 3, 4])
np.mean(a) 


2.5

In [4]:
# np.average()
# Purpose: Calculates a weighted average, where each element can contribute differently based on its weight.
# Syntax: np.average(array, weights=None, axis=None)
# weights: Supports weighting via the weights parameter. If weights are provided, elements are multiplied by their respective weights before calculating the average.
# Use Case: Use when you need to compute a weighted average, where some elements are more significant than others.
# Example:
a = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
np.average(a, weights=weights) 


3.0

In [ ]:
# When to Use One Over the Other:
# Use np.mean() when you want a simple, unweighted average.
# Use np.average() when you need to compute a weighted average, giving different importance to elements based on their weights.
# If no weights are specified, np.average() behaves like np.mean().

In [6]:
# Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

# the methods to reverse arrays in different dimensions:
# 1. Using Slicing ([::-1])
# Slicing allows reversing the array by specifying the step as -1. This works for both 1D and multi-dimensional arrays.

# 1D example
import numpy as np
a = np.array([1, 2, 3, 4, 5])
reversed_a = a[::-1]
print(reversed_a)  


[5 4 3 2 1]


In [8]:
# 2D Example (reverse row)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = a[::-1]
print(reversed_rows)




[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [12]:
# 2. Using np.flip()
#np.flip() reverses the array along any specified axis.

# 1D Array Example:
a = np.array([1, 2, 3, 4, 5])
reversed_a = np.flip(a)
print(reversed_a)


[5 4 3 2 1]


In [14]:
# 2D example ( reverse row)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = np.flip(a, axis=0)
print(reversed_rows)



[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [16]:
# 3. Using np.flipud() and np.fliplr()
# np.flipud(): Flips an array vertically (upside down) along the first axis (rows).
# np.fliplr(): Flips an array horizontally (left to right) along the second axis (columns).

# 2D Array Example (Flip Vertically):
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_ud = np.flipud(a)
print(flipped_ud)



[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [21]:
# Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#we can determine the data type of elements in a NumPy array using the .dtype attribute.
# Example:
import numpy as np
a = np.array([1, 2, 3])
print(a.dtype)  


int32


In [ ]:
# Importance of Data Types in Memory Management and Performance:
#1.Memory Efficiency: NumPy arrays use fixed-size data types (like int32, float64), which allows for compact storage and more efficient use of memory. Smaller data types (e.g., int8 vs. int64) consume less memory, which is important for large datasets.
#2.Performance: Operations on arrays with smaller data types can be faster, as they require less memory access and computation. Choosing the appropriate data type ensures that the code runs efficiently, especially in performance-critical applications.
#3.Precision Control: For numerical computations, selecting the right data type ensures that calculations have sufficient precision (e.g., float32 vs. float64 for decimal numbers) without wasting memory.
#4.Compatibility: Using correct data types helps in avoiding errors when interfacing with other libraries, which may expect specific types for performance or precision reasons.

In [24]:
# Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# In NumPy, an ndarray (short for N-dimensional array) is a fundamental data structure that represents a multi-dimensional,
# homogeneous array of fixed-size items. It is the backbone of most numerical and data manipulation tasks in NumPy.

#Key Features of ndarrays:
#1.Multi-dimensional: Unlike Python lists, which are inherently 1D, ndarrays can be multi-dimensional (1D, 2D, 3D, or more). This makes them ideal for representing matrices, tensors, and other higher-dimensional data.
#2.Homogeneous Data: All elements in an ndarray are of the same data type (e.g., int32, float64), which optimizes memory usage and computational speed.
#3.Efficient Memory Layout: Ndarrays store elements in contiguous blocks of memory, allowing for efficient access and operations, unlike Python lists, which are arrays of pointers to objects.
#4.Broadcasting: Ndarrays support broadcasting, allowing operations on arrays of different shapes without needing to manually reshape them.
#5.Vectorized Operations: Arithmetic and mathematical operations can be performed element-wise on entire arrays without using loops, leading to faster execution.
#6.Shape and Size: Ndarrays have built-in attributes like .shape (the dimensions of the array) and .size (total number of elements), making it easy to manage and manipulate data.
#7.Slicing and Indexing: You can access and modify specific elements, rows, columns, or sub-arrays using slicing and advanced indexing techniques.

#NumPy arrays (ndarrays) and Python lists have several key differences:
#1.Data Type: NumPy arrays are homogeneous, meaning all elements must be of the same data type (e.g., all integers or floats). In contrast, Python lists can hold elements of different types (e.g., a mix of integers, strings, and floats).
#2.Memory Usage: NumPy arrays are more memory-efficient because they store data in contiguous blocks of memory. Python lists are less efficient because they store pointers to objects, which adds overhead.
#3.Speed: NumPy arrays are faster for numerical operations due to their efficient memory usage and support for vectorized operations. Python lists are slower, especially for large datasets, since numerical tasks require looping through elements manually.
#4.Dimensionality: NumPy arrays can be multi-dimensional (1D, 2D, 3D, etc.), making them ideal for working with matrices and higher-dimensional data. Python lists are typically 1D, and multi-dimensional lists require nesting, which is less efficient.
#5.Mathematical Operations: With NumPy arrays, you can perform element-wise mathematical operations directly (e.g., adding arrays). With Python lists, you need to use loops or list comprehensions to perform similar operations.
#6.Flexibility: Python lists are more flexible as they can store mixed data types and easily change size. NumPy arrays, on the other hand, are less flexible because they are fixed in size and require all elements to be of the same type.
# Example :
import numpy as np
# ndarray
arr = np.array([1, 2, 3, 4])
print(arr + 2) 

# Python list
lst = [1, 2, 3, 4]
print([x + 2 for x in lst])



[3 4 5 6]
[3, 4, 5, 6]


In [ ]:
# Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#NumPy arrays provide significant performance advantages over Python lists for large-scale numerical operations due to several key factors:
#1.Memory Efficiency: NumPy arrays use contiguous blocks of memory to store elements of the same type, which reduces memory overhead and fragmentation. In contrast, Python lists are made up of pointers to objects, which consume more memory.
#2.Vectorization: NumPy allows for vectorized operations, enabling you to perform calculations on entire arrays without explicit loops. This results in faster execution because the operations are executed in optimized C/Fortran code, bypassing the overhead of Python’s interpreter.
#3.Optimized Mathematical Functions: NumPy includes a wide range of built-in functions for mathematical and statistical operations (e.g., np.sum(), np.mean()), which are implemented in a highly efficient manner. Python lists require manual looping or external libraries to perform similar tasks, which are generally slower.
#4.Broadcasting: NumPy supports broadcasting, allowing operations on arrays of different shapes without the need for manual reshaping. This feature optimizes performance by minimizing the creation of temporary arrays.
#5.Cache Efficiency: Because NumPy arrays store elements in contiguous memory, they make better use of CPU caches, leading to faster access times during computations. Python lists do not have this advantage, making them less efficient for large data sets.
#6.Parallelization: NumPy can leverage parallel processing and hardware-level optimizations, such as SIMD (Single Instruction, Multiple Data), to speed up computations on large arrays. Python lists do not have these optimizations.



In [26]:
# Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

# 1. vstack()
#Purpose: Stacks arrays in sequence vertically (row-wise).
#Usage: Takes a sequence of arrays and stacks them as new rows.
#Example:
import numpy as np

# Define two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically
vstack_result = np.vstack((a, b))
print("Vertical Stack Result:")
print(vstack_result)


Vertical Stack Result:
[[1 2 3]
 [4 5 6]]


In [28]:
# 2. hstack()
#Purpose: Stacks arrays in sequence horizontally (column-wise).
#Usage: Takes a sequence of arrays and stacks them as new columns.
#Example:
import numpy as np

# Define two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack horizontally
hstack_result = np.hstack((a, b))
print("Horizontal Stack Result:")
print(hstack_result)


Horizontal Stack Result:
[1 2 3 4 5 6]


In [42]:
# Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
#In NumPy, the fliplr() and flipud() methods are used to flip arrays, but they operate in different directions and have different effects based on the dimensions of the array.
# 1. fliplr()
#Purpose: Flips an array from left to right (horizontally).
#Effect: The columns of the array are reversed, while the rows remain unchanged.
# 2. flipud()
#Purpose: Flips an array from up to down (vertically).
#Effect: The rows of the array are reversed, while the columns remain unchanged.

#Effects on Various Array Dimensions
#1D Arrays:
#Both fliplr() and flipud() have the same effect since there is only one dimension to flip.
#2D Arrays:
#fliplr() reverses the columns.
#flipud() reverses the rows.
#3D Arrays:
#For 3D arrays, fliplr() and flipud() operate on the last two dimensions (i.e., flipping is done layer by layer):
#fliplr() flips each 2D slice in the 3D array along the left-right axis.
#flipud() flips each 2D slice along the up-down axis.
# example:
array_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]])

print("Original 3D Array:")
print(array_3d)

print("\nFlipped Left-Right (fliplr):")
print(np.fliplr(array_3d))

print("\nFlipped Up-Down (flipud):")
print(np.flipud(array_3d))





Original 3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Flipped Left-Right (fliplr):
[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]

Flipped Up-Down (flipud):
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


In [44]:
# Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. 
#Unlike the split() method, which requires the splits to be of equal size, array_split() can handle uneven splits, making it more flexible.
#Functionality of array_split()
#Basic Usage:
#The primary function of array_split() is to divide an input array into a specified number of equal (or nearly equal) sub-arrays.
#If the array cannot be divided evenly, it distributes the elements as evenly as possible across the sub-arrays. 
#Parameters:
#ary: The input array you want to split.
#indices_or_sections: This can be an integer (the number of sub-arrays) or a 1D array of indices at which to split the array.
#axis: The axis along which to split the array. The default is 0 (along the first axis).
#Return Value:
#It returns a list of sub-arrays.
#Handling Uneven Splits
#When you specify an integer for indices_or_sections and the array cannot be evenly divided, array_split() will create sub-arrays with sizes that differ by at most one element. Here’s how it works:

#If you have an array of size n and want to split it into 𝑘 sub-arrays, the sizes of the resulting sub-arrays will be distributed as evenly as possible.
#For example, if 𝑛 =10 and 𝑘=3, the resulting sub-arrays might have sizes 4, 3, and 3.
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result_uneven = np.array_split(array, 4)
print("Uneven Split Result:")
print(result_uneven)


Uneven Split Result:
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [46]:
# Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
#1. Vectorization
#Definition: Vectorization refers to the process of replacing explicit loops in numerical computations with array operations. Instead of iterating over each element in an array and performing calculations using Python loops, vectorized operations enable you to apply functions to entire arrays at once.
#Benefits:
#Performance: Vectorized operations are implemented in low-level languages (like C) and are optimized for performance. They execute much faster than Python loops due to reduced overhead.
#Readability: Code using vectorized operations is often more concise and easier to read, as it eliminates the need for explicit iteration.
# example :
import numpy as np
a = np.array([1, 2, 3, 4, 5])

# Vectorized operation (adding 10 to each element)
result = a + 10
print(result)  


[11 12 13 14 15]


In [48]:
#2. Broadcasting
#Definition: Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes without explicitly reshaping them.
#When operating on arrays of different dimensions, NumPy automatically expands the smaller array to match the shape of the larger array.
#mechanism :
#NumPy compares the shapes of the two arrays involved in the operation from the trailing dimensions (rightmost).
#If the dimensions are equal or one of them is 1, NumPy can “broadcast” the smaller array to match the larger array's shape.
#This process enables operations on arrays that are not explicitly the same size, making it highly efficient.
# example:
import numpy as np

# Define a 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define a 1D array
b = np.array([10, 20, 30])

# Broadcasting: b is automatically expanded to match a's shape
result = a + b
print(result)


[[11 22 33]
 [14 25 36]]


In [ ]:
#Contributions to Efficient Array Operations:
#1.Performance: Both vectorization and broadcasting minimize the need for Python-level loops and overhead, allowing operations to be executed in optimized, compiled code. This leads to substantial performance improvements, especially for large datasets.
#2.Memory Efficiency: Broadcasting avoids the need to create additional copies of data in memory, as it operates on the original arrays with minimal memory overhead. This is particularly useful when working with large arrays.
#3.Concise Code: Vectorized operations and broadcasting enable developers to write cleaner and more maintainable code. Instead of writing complex loops for element-wise operations, you can leverage these features to express operations in a more straightforward manner.
#4.Scalability: These concepts make it easier to scale computations on larger arrays, as they are designed to handle varying shapes and sizes without losing efficiency.


In [ ]:
# PRACTICAL QUESTIONS 

In [50]:
# Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original Array:")
print(array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array_3x3)

# Print the transposed array
print("\nTransposed Array (Interchanged Rows and Columns):")
print(transposed_array)


Original Array:
[[94 34 16]
 [15 33 89]
 [96 93 16]]

Transposed Array (Interchanged Rows and Columns):
[[94 15 96]
 [34 33 93]
 [16 89 16]]


In [52]:
# Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements from 0 to 9

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("Original 1D Array:")
print(array_1d)

print("\nReshaped to 2x5 Array:")
print(array_2x5)

print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [56]:
# Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it, resulting in a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and padded arrays
print("Original 4x4 Array with Random Float Values:")
print(array_4x4)

print("\n6x6 Array with a Border of Zeros:")
print(array_with_border)


Original 4x4 Array with Random Float Values:
[[0.83544088 0.22351842 0.25401056 0.90703651]
 [0.901054   0.51747187 0.8727801  0.06904776]
 [0.15759429 0.00324056 0.26709855 0.93584715]
 [0.87701961 0.77265673 0.41315718 0.48587385]]

6x6 Array with a Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.83544088 0.22351842 0.25401056 0.90703651 0.        ]
 [0.         0.901054   0.51747187 0.8727801  0.06904776 0.        ]
 [0.         0.15759429 0.00324056 0.26709855 0.93584715 0.        ]
 [0.         0.87701961 0.77265673 0.41315718 0.48587385 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [58]:
# Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Print the resulting array
print(array_integers)


[10 15 20 25 30 35 40 45 50 55 60]


In [60]:
# Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element. 
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)    
lowercase_array = np.char.lower(string_array)    
titlecase_array = np.char.title(string_array)     
capitalize_array = np.char.capitalize(string_array)  
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)
print("Capitalize:", capitalize_array)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


In [62]:
# Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', words_array)
print(spaced_array)


['p y t h o n' 'n u m p y' 'p a n d a s']


In [66]:
# Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9], 
                   [10, 11, 12]])

# Perform element-wise operations
addition_result = array1 + array2          # Addition
subtraction_result = array1 - array2       # Subtraction
multiplication_result = array1 * array2    # Multiplication
division_result = array1 / array2          # Division
print("Addition:\n", addition_result)
print("Subtraction:\n", subtraction_result)
print("Multiplication:\n", multiplication_result)
print("Division:\n", division_result)


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [68]:
# Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
diagonal_elements = np.diagonal(identity_matrix)
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [70]:
# Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers: [343 286 813 380 458 949 459 165 633 122 327 326 526 229 855 220 457 195
 386 573 865 574 681 116  93 542 265 747 841 259 188 832 212 910 896 275
 713 434 381 212 965 593 132 918  38 535 707  92 823 784 609 590  91  47
 121 713 509 701 839 822 448 303 986 313 820 703  60 385 325 902  87 174
 305 864 332 950 951 247 790 888 870 543 209 394  73 879 612 786 624 610
 174 690 685 473 421 470 887 738 420 257]
Prime Numbers: [229, 457, 593, 823, 47, 509, 701, 839, 313, 73, 421, 887, 257]


In [78]:
# Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, generating random temperatures between 15 and 30 degrees Celsius
daily_temperatures = np.random.randint(15, 31, size=30)

# Reshape the array into weeks (4 weeks, with 2 days in the last week)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)




ValueError: cannot reshape array of size 30 into shape (4,7)